import type { Task, User } from '../types';

export const MOCK_USERS: User[] = [
    {
        id: 'u1',
        name: 'Alex Johnson',
        email: 'alex@college.edu',
        avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Alex',
        rating: 4.8,
        reviews: 12,
        skills: ['Coding', 'React', 'Python'],
    },
    {
        id: 'u2',
        name: 'Sarah Smith',
        email: 'sarah@college.edu',
        avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Sarah',
        rating: 4.9,
        reviews: 24,
        skills: ['Writing', 'Design', 'PowerPoint'],
    },
    {
        id: 'u3',
        name: 'Mike Chen',
        email: 'mike@college.edu',
        avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Mike',
        rating: 4.5,
        reviews: 8,
        skills: ['Math', 'Tutoring'],
    },
    {
        id: 'u4',
        name: 'Emily Davis',
        email: 'emily@college.edu',
        avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Emily',
        rating: 4.7,
        reviews: 15,
        skills: ['Art', 'Design'],
    },
];

export const MOCK_TASKS: Task[] = [
    {
        id: 't1',
        title: 'Need help with Data Structures Assignment',
        description: 'I need someone to help me implement a Red-Black Tree in C++. Due in 2 days.',
        category: 'Coding',
        price: 500,
        deadline: '2023-12-05',
        status: 'Open',
        author: MOCK_USERS[0],
        createdAt: '2023-12-01T10:00:00Z',
    },
    {
        id: 't2',
        title: 'Print Lab Manual - 50 Pages',
        description: 'Need color print of my Physics lab manual. Drop off at Block A, Room 302.',
        category: 'Printing',
        price: 150,
        deadline: '2023-12-02',
        status: 'Open',
        author: MOCK_USERS[1],
        createdAt: '2023-12-01T12:00:00Z',
        printOptions: {
            color: true,
            sides: 'double',
            binding: true,
            copies: 1,
            dropOffLocation: 'Block A, Room 302',
            fileUrl: 'lab_manual.pdf',
        },
    },
    {
        id: 't3',
        title: 'Chemistry Project PPT',
        description: 'Need a 15-slide presentation on Organic Chemistry topics. I have the content, just need design.',
        category: 'PPT',
        price: 300,
        deadline: '2023-12-04',
        status: 'Open',
        author: MOCK_USERS[0],
        createdAt: '2023-12-01T14:00:00Z',
    },
];
